# -*- mode:python -*-

# Copyright (c) 2024 ProteusLab
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os

Import('env')

protea_root = Dir('.').srcnode().abspath
protea_repo = os.path.join(protea_root, 'Protea')

if not os.path.exists(os.path.join(protea_repo, 'CMakeLists.txt')):
    env['HAVE_PROTEA'] = False
    print("Protea: not found (clone into ext/protea/Protea/)")
    Return()

env['HAVE_PROTEA'] = True
print(f"Protea: found at {protea_repo}")

env['PROTEA_ROOT'] = protea_repo
env['PROTEA_SIM_LIB_DIR'] = os.path.join(protea_repo, 'sim_lib')
env['PROTEA_SIM_GEN_DIR'] = os.path.join(protea_repo, 'sim_gen')
env['PROTEA_LIB_DIR'] = os.path.join(protea_repo, 'lib')
env['PROTEA_LIRA_RUBY_DIR'] = os.path.join(protea_repo, 'lib', 'lira')
